### ISSUE TITLE
No barcodes showing up in new barcodes

### ISSUE THREAD

**Issue by geraldbrent1** [Forceu/barcodebuddy#110]
![7A3B8E65-8BB1-4D05-955D-31F0A3A8048D](https://user-images.githubusercontent.com/27817496/105803902-10505300-5f64-11eb-8dd3-3e6813e90744.jpeg)

I recently installed Barcode Buddy to help with the daunting task of putting things into Grocy. After getting everything talking across dockers, I noticed that after scanning random things around my home, they were showing up in processed as unknown, but not appearing in the list for import into Grocy. Am I doing something wrong, or is this intended?

**Comment by Forceu** [comment]
Thank you for report! I was able to reproduce it and it has been fixed in f8dee69c5cce3510ba03cd367dc7ba61d3dc4a62.

The reason for this problem was that the database was incorrectly initialised for new users, and it didn't affect me during testing as I was using my old database that got updated. I will release an updated version, the docker image should be up in 5-10 minutes.

**Comment by llewy** [comment]
Still have this problem with 1.8.0.2 after updating from 1.6*. Any suggestions?

**Comment by Forceu** [comment]
Thanks for the comment, I will investigate this issue further...

**Comment by Forceu** [comment]
Okay, I am still unable to reproduce this problem with an installation that upgraded from 1.6.5.2 to 1.8.0.2, but if anyone is expierincing the same problem, please comment below!
